version: 1.0
provider:
  name: openfaas
  gateway: http://10.141.212.140:31112
functions:
  init-config-mongo:
    lang: java8
    handler: ./init-config-mongo
    image: 286071421/init-config-mongo:latest

